[package]
name = "seqdiff"
version = "0.1.0"
authors = ["Yohei Tamura <tamuhey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]

quickcheck_macros = "0.9.1"    
quickcheck = "0.9.2"   